# site settings
title: Manasi Mankad
subtitle: Product Designer
email: manasimankad@gmail.com
description: I'm a Digital Product Designer currently working at Schlumberger, Pune
baseurl: "" # the subpath of your site, e.g. /blog
url: manasimankad.github.io # the base hostname & protocol for your site
author: Manasi Mankad
street_address: 
city: 
state: 
zip_code: 
country: 
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 0

# social settings

instagram_url: https://instagram.com/manasi.mankad
linkedin_url: https://www.linkedin.com/in/manasi-mankad-31963a51/

# build settings
markdown: kramdown

sass:
  style: compressed
